[Export]
baked_state = false
baked_notebookfile = false
offer_binder = true
ignore_cache = [
    "index.jl",
]
create_index = false
exclude = [
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
]
