name: Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:
concurrency:
    group: export
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: 🙌 Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: "1.9"

            - name: ⏱ Cache notebook states
              uses: actions/cache@v2
              with:
                path: _cache
                key: ${{ runner.os }}-pluto_state_cache-v1-bioinfospec-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v1-bioinfospec-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: ⏱ Cache .julia
              uses: actions/cache@v2
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: 🪴 Generate site
              run: julia --project=pluto-deployment-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  include("./generate.jl")'

            
            - name: 📰 Upload site generation report
              uses: actions/upload-artifact@v2
              if: always()
              with:
                path: generation_report.html

            - name: 🚀 Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: publish
